import streamlit as st

st.set_page_config(
    page_title="Moza R3 ACC Force Calculator",
    page_icon="🏎️",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("🏎️ Moza R3 & ACC Advanced Physics Calculator")
st.markdown("Calculates active DirectInput telemetry spikes versus resistive steering weight (damping/friction).")
st.markdown("---")

MAX_TORQUE_NM = 3.9

# --- MOZA PIT HOUSE SIDEBAR ---
st.sidebar.header("🔧 MOZA PIT HOUSE")
st.sidebar.subheader("Basic Settings")
moza_ffb = st.sidebar.slider("Game FFB Intensity (%)", 0, 100, 100)
moza_road_sens = st.sidebar.slider("Road Sensitivity (0-10)", 0, 10, 10)
moza_max_speed = st.sidebar.slider("Maximum Wheel Speed (%)", 10, 140, 100)
moza_damper = st.sidebar.slider("Wheel Damper (%)", 0, 100, 30)

st.sidebar.subheader("Advanced Settings")
moza_torque_limit = st.sidebar.slider("Max Output Torque Limit (%)", 50, 100, 100)
moza_inertia = st.sidebar.slider("Natural Inertia (%)", 100, 500, 150, 10)
moza_friction = st.sidebar.slider("Wheel Friction (%)", 0, 100, 15)
moza_speed_damp = st.sidebar.slider("Speed-dependent Damping (%)", 0, 100, 30)

st.sidebar.subheader("🎚️ FFB Equalizer")
eq_15hz = st.sidebar.slider("15 Hz (Bumps/Weight Transfer) (%)", 0, 500, 100, 10)
eq_25hz = st.sidebar.slider("25 Hz (Curbs/ABS) (%)", 0, 500, 100, 10)
eq_40hz = st.sidebar.slider("40 Hz (Rumble Strips) (%)", 0, 500, 100, 10)
eq_60hz = st.sidebar.slider("60 Hz (Road Textures) (%)", 0, 500, 100, 10)
eq_100hz = st.sidebar.slider("100 Hz (Micro-vibrations) (%)", 0, 500, 100, 10)

# --- ACC SIDEBAR ---
st.sidebar.header("🎮 ACC SETTINGS")
acc_gain = st.sidebar.slider("Gain (%)", 0, 100, 80)
acc_dynamic_damping = st.sidebar.slider("Dynamic Damping (%)", 0, 100, 100)
acc_road_effects = st.sidebar.slider("Road Effects (Canned) (%)", 0, 100, 0)

# --- MATHEMATICAL ENGINES ---
base_scalar = (acc_gain / 100.0) * (moza_ffb / 100.0) * (moza_torque_limit / 100.0)
road_sens_scalar = moza_road_sens / 10.0

# Telemetry Phases (Active Forces)
telemetry_phases = {
    "Front Tire Grip (Peak Cornering Load)": {"raw": 1.0, "eq": 1.0, "sens": 1.0},
    "First Stage Understeer (Initial Slip)": {"raw": 0.70, "eq": 1.0, "sens": 1.0},
    "Second Stage Understeer (Severe Washout)": {"raw": 0.40, "eq": 1.0, "sens": 1.0},
    "Rear Tire Sliding (Snap Oversteer Aligning)": {"raw": 0.90, "eq": 1.0, "sens": 1.0},
    "Braking Weight Transfer (Forward Pitch)": {"raw": 0.40, "eq": eq_15hz / 100.0, "sens": 1.0},
    "Suspension Bumps / Dips": {"raw": 0.40, "eq": eq_15hz / 100.0, "sens": 1.0},
    "Direct Curb Strikes (Apex)": {"raw": 0.60, "eq": eq_25hz / 100.0, "sens": 1.0},
    "Rumble Strips (Corrugated Ripple)": {"raw": 0.30, "eq": eq_40hz / 100.0, "sens": road_sens_scalar}
}

# --- UI LAYOUT ---
col_forces, col_resistance = st.columns(2)

with col_forces:
    st.header("⚡ Active Telemetry Forces")
    st.write("Raw physics forces generated by the steering rack, scaled by Gain and EQ.")
    
    for name, data in telemetry_phases.items():
        force_nm = data["raw"] * base_scalar * data["eq"] * data["sens"] * MAX_TORQUE_NM
        force_nm = min(force_nm, MAX_TORQUE_NM) # Hard cap clipping
        
        st.write(f"**{name}**: {force_nm:.3f} Nm")
        st.progress(force_nm / MAX_TORQUE_NM)

    # Artificial Road Effects is calculated entirely separately from physics telemetry
    artificial_nm = 0.10 * (acc_road_effects / 100.0) * base_scalar * (eq_100hz / 100.0) * road_sens_scalar * MAX_TORQUE_NM
    artificial_nm = min(artificial_nm, MAX_TORQUE_NM)
    st.write(f"**Artificial Road Effects (Canned Layer)**: {artificial_nm:.3f} Nm")
    st.progress(artificial_nm / MAX_TORQUE_NM)

with col_resistance:
    st.header("🧱 Resistive Steering Weight")
    st.write("These settings do not create active FFB spikes. They create mechanical resistance (weight) against your hands at high speeds.")
    
    # Resistance calculations based on max torque capacity
    fric_nm = 0.05 * (moza_friction / 100.0) * MAX_TORQUE_NM
    damp_nm = 0.10 * (moza_damper / 100.0) * MAX_TORQUE_NM
    acc_dyn_nm = 0.15 * (acc_dynamic_damping / 100.0) * MAX_TORQUE_NM
    moza_speed_nm = 0.10 * (moza_speed_damp / 100.0) * MAX_TORQUE_NM
    
    total_resistance = min(fric_nm + damp_nm + acc_dyn_nm + moza_speed_nm, MAX_TORQUE_NM)
    
    st.metric("Total High-Speed Resistance", f"{total_resistance:.3f} Nm")
    st.progress(total_resistance / MAX_TORQUE_NM)
    
    with st.expander("Breakdown of Resistive Forces", expanded=True):
        st.write(f"- **Static Friction:** {fric_nm:.3f} Nm")
        st.write(f"- **Static Damper:** {damp_nm:.3f} Nm")
        st.write(f"- **ACC Dynamic Damping (High Speed):** {acc_dyn_nm:.3f} Nm")
        st.write(f"- **Moza Speed Damping (High Speed):** {moza_speed_nm:.3f} Nm")

    st.info(f"**Note on Wheel Speed:** Your max wheel speed is restricted to **{moza_max_speed}%**. This caps how violently the {MAX_TORQUE_NM} Nm motor can snap the wheel during oversteer corrections.")
